// ── Team Members Data ──────────────────────────────────────────
export const TEAM_MEMBERS = [
  {
    id: 'p1',
    index: '01 / 05',
    name: 'Rajat Singh',
    role: 'Backend Developer',
    headline: ['Powering', 'the Core.'],
    description:
      'Rajat designs and maintains scalable backend systems that power the platform’s core functionality. He focuses on performance optimization, secure APIs, and reliable data flow between services, ensuring the system remains fast and fault-tolerant under heavy load.',
    meta: [
      { label: 'Based in', value: 'India' },
      { label: 'Specialization', value: 'Server-side Architecture' },
      { label: 'Experience', value: '5+ years' },
      { label: 'APIs Built', value: '40+ services' },
    ],
    skills: ['Node.js', 'Databases', 'API Design', 'System Architecture'],
    accentColor: 'rgba(79,143,255',
    planet: {
      baseColor: '#1a3a80',
      bands: ['#1e4a9a', '#2255aa', '#184088', '#162e6a'],
      atmosColor: 'rgba(60,120,255,0.18)',
      glowColor: 'rgba(79,143,255,0.35)',
      rings: false,
    },
    orbitSpeed: '7s',
    orbitColor: 'rgba(79,143,255,0.15)',
    satColor: '#7fb3ff',
    satGlow: '#4f8fff',
    roleDotColor: '#4f8fff',
    roleDotGlow: 'rgba(79,143,255,0.6)',
    roleTextColor: 'rgba(79,143,255,0.65)',
    skillStyle: {
      bg: 'rgba(79,143,255,0.07)',
      border: 'rgba(79,143,255,0.13)',
      color: 'rgba(79,143,255,0.65)',
    },
  },

  {
    id: 'p2',
    index: '02 / 05',
    name: 'Praduman Sachan',
    role: 'Model Trainer',
    headline: ['Training', 'Intelligence.'],
    description:
      'Praduman focuses on training and fine-tuning machine learning models to achieve high accuracy and reliability. He works closely with data pipelines, evaluates model performance, and iterates rapidly to improve prediction quality across real-world datasets.',
    meta: [
      { label: 'Based in', value: 'India' },
      { label: 'Domain', value: 'Machine Learning' },
      { label: 'Experience', value: '4+ years' },
      { label: 'Models Trained', value: '25+ models' },
    ],
    skills: ['Model Training', 'Data Preprocessing', 'Evaluation Metrics', 'Python'],
    accentColor: 'rgba(167,139,250',
    planet: {
      baseColor: '#3a1060',
      bands: ['#4a1878', '#552288', '#3a0e60', '#2c0a50'],
      atmosColor: 'rgba(150,90,255,0.18)',
      glowColor: 'rgba(167,139,250,0.35)',
      rings: false,
    },
    orbitSpeed: '9s',
    orbitColor: 'rgba(167,139,250,0.15)',
    satColor: '#c4aeff',
    satGlow: '#a78bfa',
    roleDotColor: '#a78bfa',
    roleDotGlow: 'rgba(167,139,250,0.6)',
    roleTextColor: 'rgba(167,139,250,0.65)',
    skillStyle: {
      bg: 'rgba(167,139,250,0.07)',
      border: 'rgba(167,139,250,0.13)',
      color: 'rgba(167,139,250,0.65)',
    },
  },

  {
    id: 'p3',
    index: '03 / 05',
    name: 'Aryan',
    role: 'ML Engineer',
    headline: ['Engineering', 'Intelligence.'],
    description:
      'Aryan builds end-to-end machine learning solutions, from feature engineering to deployment. He bridges the gap between research and production, ensuring models are scalable, efficient, and production-ready.',
    meta: [
      { label: 'Based in', value: 'Bangalore, IN' },
      { label: 'Focus', value: 'ML Systems' },
      { label: 'Experience', value: '5 years' },
      { label: 'Models Deployed', value: '18+' },
    ],
    skills: ['Machine Learning', 'Model Deployment', 'Python', 'Data Pipelines'],
    accentColor: 'rgba(56,217,169',
    planet: {
      baseColor: '#0a3830',
      bands: ['#0e4a40', '#0a5848', '#083430', '#063030'],
      atmosColor: 'rgba(40,200,150,0.18)',
      glowColor: 'rgba(56,217,169,0.35)',
      rings: true,
    },
    orbitSpeed: '6s',
    orbitColor: 'rgba(56,217,169,0.15)',
    satColor: '#6eead0',
    satGlow: '#38d9a9',
    roleDotColor: '#38d9a9',
    roleDotGlow: 'rgba(56,217,169,0.6)',
    roleTextColor: 'rgba(56,217,169,0.65)',
    skillStyle: {
      bg: 'rgba(56,217,169,0.07)',
      border: 'rgba(56,217,169,0.13)',
      color: 'rgba(56,217,169,0.65)',
    },
  },

  {
    id: 'p4',
    index: '04 / 05',
    name: 'Abhay Singh Tomar',
    role: 'Front-end Developer',
    headline: ['Crafting', 'Interfaces.'],
    description:
      'Abhay builds responsive, interactive, and visually polished user interfaces. He focuses on performance, accessibility, and smooth animations to deliver seamless user experiences across modern web platforms.',
    meta: [
      { label: 'Based in', value: 'India' },
      { label: 'Stack', value: 'React / GSAP / Tailwind' },
      { label: 'Experience', value: '3+ years' },
      { label: 'UI Projects', value: '20+' },
    ],
    skills: ['React', 'JavaScript', 'Animations', 'UI/UX'],
    accentColor: 'rgba(196,122,53',
    planet: {
      baseColor: '#5a2a08',
      bands: ['#7a3a10', '#6a3010', '#502208', '#401a06'],
      atmosColor: 'rgba(200,120,40,0.18)',
      glowColor: 'rgba(196,122,53,0.35)',
      rings: false,
    },
    orbitSpeed: '11s',
    orbitColor: 'rgba(196,122,53,0.15)',
    satColor: '#e0a060',
    satGlow: '#c47a35',
    roleDotColor: '#c47a35',
    roleDotGlow: 'rgba(196,122,53,0.6)',
    roleTextColor: 'rgba(196,122,53,0.65)',
    skillStyle: {
      bg: 'rgba(196,122,53,0.07)',
      border: 'rgba(196,122,53,0.13)',
      color: 'rgba(196,122,53,0.65)',
    },
  },

  {
    id: 'p5',
    index: '05 / 05',
    name: 'Suryansh Tiwari',
    role: 'Research',
    headline: ['Exploring', 'Possibilities.'],
    description:
      'Suryansh conducts in-depth research to explore new technologies and methodologies. He analyzes trends, validates ideas through experimentation, and supports innovation with strong theoretical foundations.',
    meta: [
      { label: 'Based in', value: 'India' },
      { label: 'Field', value: 'Technical Research' },
      { label: 'Experience', value: '6+ years' },
      { label: 'Research Papers', value: '10+' },
    ],
    skills: ['Research', 'Analysis', 'Documentation', 'Problem Solving'],
    accentColor: 'rgba(192,84,184',
    planet: {
      baseColor: '#4a0a48',
      bands: ['#5e1060', '#6a1468', '#3e0840', '#300636'],
      atmosColor: 'rgba(200,60,190,0.18)',
      glowColor: 'rgba(192,84,184,0.35)',
      rings: false,
    },
    orbitSpeed: '8s',
    orbitColor: 'rgba(192,84,184,0.15)',
    satColor: '#d880d0',
    satGlow: '#c054b8',
    roleDotColor: '#c054b8',
    roleDotGlow: 'rgba(192,84,184,0.6)',
    roleTextColor: 'rgba(192,84,184,0.65)',
    skillStyle: {
      bg: 'rgba(192,84,184,0.07)',
      border: 'rgba(192,84,184,0.13)',
      color: 'rgba(192,84,184,0.65)',
    },
  },
];

// ── Research Section Data ──────────────────────────────────────
export const RESEARCH_LINKS = [
  {
    title: 'Datasets',
    items: [
      { name: 'Exoplanet Catalogue',  desc: '4,200+ confirmed targets', href: '#' },
      { name: 'Spectral Atlas',       desc: 'UV–IR stellar spectra',    href: '#' },
      { name: 'Mission Telemetry',    desc: 'All 14 completed missions', href: '#' },
      { name: 'Dark Matter Maps',     desc: 'Large-scale structure grids', href: '#' },
      { name: 'Orbital Ephemeris',    desc: 'Daily updated positions',  href: '#' },
    ],
  },
  {
    title: 'APIs',
    items: [
      { name: 'Telemetry API',        desc: 'Live & historical streams', href: '#' },
      { name: 'Orbit Predictor',      desc: 'REST · trajectory models', href: '#' },
      { name: 'Spectroscopy API',     desc: 'Query stellar signatures', href: '#' },
      { name: 'Anomaly Detector',     desc: 'ML-powered alerts',        href: '#' },
      { name: 'Propulsion Sim',       desc: 'Ion thruster models',      href: '#' },
    ],
  },
  {
    title: 'Publications',
    items: [
      { name: 'Dark Matter Distribution', desc: 'Nature Astronomy · 2023', href: '#' },
      { name: 'Ion Thruster Efficiency',  desc: 'AIAA Journal · 2023',     href: '#' },
      { name: 'Fault-Tolerant GNC',       desc: 'IEEE Aerosp. · 2022',     href: '#' },
      { name: 'Exoplanet Habitability',   desc: 'ApJ Letters · 2022',      href: '#' },
      { name: 'ML Anomaly Detection',     desc: 'Acta Astronautica · 2024', href: '#' },
    ],
  },
  {
    title: 'Resources',
    items: [
      { name: 'Developer Docs',       desc: 'API reference & SDKs',    href: '#' },
      { name: 'GitHub',               desc: 'Open-source tools',       href: '#' },
      { name: 'Mission Archive',      desc: 'Raw data repository',     href: '#' },
      { name: 'Community Forum',      desc: 'Researchers & devs',      href: '#' },
      { name: 'Press & Media',        desc: 'Coverage & releases',     href: '#' },
    ],
  },
];
